### ISSUE TITLE
Add Post Device Update (Single Values to Multiple Streams)

### ISSUE THREAD

**Issue by kristinpeterson** [attm2x/m2x-arm-mbed#2]
Add [Post Device Update (Single Values to Multiple Streams)](https://m2x.att.com/developer/documentation/v2/device#Post-Device-Update--Single-Values-to-Multiple-Streams-) endpoint to the following client libraries, method should be named `postDeviceUpdate`

**Comment by xxuejie** [comment]
As of release 2.1.2, this has been fixed. Though the function is named `postSingleDeviceUpdate` so as to avoid typo problem with `postDeviceUpdates`.
